SVProgressHUD/SVIndefiniteAnimatedView.m, SVProgressHUD/SVProgressHUD.m
This fixes #396 for Cocoapods 0.36 beta. I didn't yet have time to test this on a static library setup, but it works nicely in my Swift application. 
There's some whitespace cleanup automatically done by the editor.
=> Fix image paths to support frameworks (and Swift) introduced in Cocoapods 0.36 beta

SVProgressHUD/SVIndefiniteAnimatedView.m, SVProgressHUD/SVProgressHUD.m
Hi there! Long-time user, first-time contributor :iphone: 
The behaviour of `imageNamed:` has changed in version 0.36 of CocoaPods (which is currently in RC 1). [This blog post](http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/) has some more details. 
Long story short: `imageNamed:` won't work in the way that the library is using them; they need to be loaded directly from the file system, instead. 
This is in lieu of #403 because I didn't see it before I made my changes, because its implementation is a bit heavy-handed, and because it is incomplete (doesn't work in the indefinite animated view class).
I'm happy to modify the code style or structure to get it merged – just let me know!
Fixes #396.
=> Fixes Frameworks' image-loading issue.

SVProgressHUD/SVProgressHUD.m
It was happen when called  showProgress:status: method after showSuccessWithStatus: method.
In case which next show method is called before starting fadeOutTimer, activityCount was remained +1.
So, fixes to set activityCount to 0 if fadeOutTimer is canceled.
=> Fixes the issues that popActivity method does not work sometimes.

SVProgressHUD/SVIndefiniteAnimatedView.m, SVProgressHUD/SVProgressHUD.m
1. Using modern syntax for NSNumber creation.
2. Replacing (id)initWithFrame with (instancetype)initWithFrame.
3. Using ivar access instead of self.property inside of the init method.
4. Harmonized self.class -> [self class] to match NSObject's defined usage.
5. Harmonized setHidden:NO -> .hidden = NO to match usage elsewhere in the project.
6. Using modern dictionary syntax in place of valueForKey.
=> Minor code syntax changes.

SVProgressHUD/SVProgressHUD.m
It was not possible to compile project in Objective-C++. Now it is.
Compiler was giving this error: "Cannot initialize a parameter of type 'NSStringDrawingOptions' with an rvalue of type 'int'"
=> Fixed semantic issue obstructing compilation in Objective-C++.

SVProgressHUD/SVProgressHUD.m
- set frame equal to windows bounds, not screen bounds
- position HUD when app becomes active
=> support iPad multitasking

SVProgressHUD/SVProgressHUD.m
If background gradient layer has already been added as a sublayer it should be removed or it would place layer upon layer every time method is called. Or it would case gradient to persist if changing type to "Black".
=> Removes an existing gradient layer if present

SVProgressHUD/SVProgressHUD.h, SVProgressHUD/SVProgressHUD.m
As discussed, here's the PR for the minor fix preventing overwriting the defaultMaskType. Haven't changed the deprecated status of those methods.
=> Fixed "withMaskType" methods so they don't overwrite defaultMaskType

SVProgressHUD/SVProgressHUD.m
Previously, if `viewForExtension` is set, the the window frame will be used to find the center of the screen, which doesn't make sense if the HUD is being positioned in a view that's smaller than the screen. 
For example, trying to show the HUD in a Safari extension on the iPad results in this (that's it down in the bottom right corner):
I added a line to use the view's frame rather than the screen's frame if a custom view is present.
=> Fix an off-center HUD when running in a Safari extension on the iPad

SVProgressHUD/SVProgressHUD.h, SVProgressHUD/SVProgressHUD.m
can be used to avoid resizing for a larger success/error message
=> Added minSize

SVProgressHUD/SVProgressHUD.m
Because it removes bg, supports only light & dark styles and thus brakes semi-transparent custom background
=> Don't apply blur for custom style

SVProgressHUD/SVProgressHUD.h, SVProgressHUD/SVProgressHUD.m
1. [SVProgress show…] // self.overlayView.superview is window1
2. [SVProgress dismiss] // it dismiss progress duration 0.15s to
completion, completion called by async.
3. new a window2 immediately。
4. [SVProgress show] // it is a bug, it is show in window1 rather than
window2. but we often like it show in window.
1.I change dimiss method interface 
`- (void)dismissWithDelay:(NSTimeInterval)delay`
to
`- (void)dismissWithDuration:(NSTimeInterval)duration delay:(NSTimeInterval)delay`,
and add a class method
`+ (void)dismissWithDuration:(NSTimeInterval)duration delay:(NSTimeInterval)delay`
2. I change dimiss method implemention
if duration == 0，sync call `animationBlock` and `completionBlock`,
if use `animateWithDuration:0
delay:delay
options:…`
the completion will call async。it maybe lead to …
=> dismiss duration 0.15 maybe lead to a bug

CHANGELOG.md
The project changelog is currently available on the repo GitHub wiki. I think it would be nicer to keep it as a dedicated file inside the repo itself
- easier to find (visible from the main page)
- no longer relies on GitHub having a wiki
- displays on CocoaPods.org (example: [AFNetworking](https://cocoapods.org/pods/AFNetworking))
- one more file in the repo
=> Move changelog to project repo

SVProgressHUD/SVProgressHUD.m
DisplayDurationForString can return value less than minimumDismissTimeInterval.
Changed 
` return MIN((float)string.length * 0.06 + 0.5, [self sharedView].minimumDismissTimeInterval);`
to
` return MAX((float)string.length * 0.06 + 0.5, [self sharedView].minimumDismissTimeInterval);`
=> Fixed problem where displayDurationForString can return duration shoter than minimumDismissTimeInterval

SVProgressHUD/SVProgressHUD.h, SVProgressHUD/SVProgressHUD.m
Allows apps to customize the color/opacity of the dimmed background when using SVProgressHUDMaskTypeBlack
Allows apps to customize the fade-in and fade-out animation speed (without calling dismissWithDuration: everywhere)
https://github.com/SVProgressHUD/SVProgressHUD/issues/564
=> Add support for dimming color and fade customizations

SVProgressHUD/SVProgressHUD.m
The opaque black and white colors were preventing the UIVisualEffectView from using the background contents in the blur. This fixes #517
=> Use clearColor as background when using a blur view. Fixes #517.

README.md, SVProgressHUD/SVProgressHUD.h, SVProgressHUD/SVProgressHUD.m
Some apps create several custom UIWindow objects and may have various window levels. maxAllowedWindowLevel will help to make things more convenient.
=> Allow to set max allowed window level

SVProgressHUD/SVProgressHUD.h, SVProgressHUD/SVProgressHUD.m
This PR adds a new setting `maximumDismissTimeInterval`. This allows to specify an interval which caps out the provided calculation at the specified interval.
``` objective-c
+ (NSTimeInterval)displayDurationForString:(NSString*)string {
return MAX((float)string.length * 0.06 + 0.5, [self sharedView].minimumDismissTimeInterval);
}
```
Note: This does **not** change the current behaviour, as the new setting defaults to `CGFLOAT_MAX`, i.e. infinite.
=> add maximum dismiss interval

LICENSE.txt
This pull request unwraps the license text.
This is purely a formal change, and I hope not too controversial. In some contexts we might want to display the license, for instance in a `UITextView`, so having artificial line breaks can become an issue.
=> Unwrap license text

SVProgressHUD/SVProgressHUD.h, SVProgressHUD/SVProgressHUD.m
This PR introduces a new appearance selector called `shouldTintImages`, which is `true` by default.
With this selector one will be able to control image rendering mode, e.g. if it's set to true `Always Template` mode with applied tint will be used, otherwise, it would be an `Always Original` mode.
This is very helpful if you have info/error/success images in different colors.
=> Image Tint Control

SVProgressHUD/SVProgressHUD.m
- Fixes an issue where the status would not be shown if it was added to a version of the HUD without any text.
- PR follow up from https://github.com/SVProgressHUD/SVProgressHUD/pull/854.
=> Show statusLabel when text is added to it.

Demo/SVProgressHUD.xcodeproj/project.pbxproj, SVProgressHUD/SVProgressHUD.m
- This commit drops support for Xcode versions below 9.
I've opened this branch following a long period of waiting for these changes in https://github.com/SVProgressHUD/SVProgressHUD/pull/821/files.
=> Use @available to suppress warnings in Xcode 9.

README.md
This just tweaks the instructions for Carthage installations to use the `bootstrap` command and to punt out the copying of the framework into an iOS / tvOS app to the Carthage documentation since it's not trivial because of Xcode specific bugs.
=> Updated README’s instructions for Carthage deployment

SVProgressHUD/SVProgressHUD.m
Issue: Voiceover users are able to access background elements when SVProgressHUDMask is set to anything.
Expectation: Voiceover user should not be able to access background elements when SVProgressHUDMask is set to anything other then None.
Fix: Setting the controlView to accessibilityViewIsModal=YES while !=SVProgressHUDMaskTypeNone blocks the user from accessing background elements with VoiceOver on.
=> AccessibilityViewIsModal for SVProgressHUDMaskType

SVProgressHUD/SVProgressHUD.h
I made enum written for Obejctive-C available with Swift style enum.
It became easier to use when using with swift.
=> To make Objective-C's enum easier to use even for swift

SVProgressHUD/SVProgressHUD.m
Remove new line character before setting accessibility text to avoid
repetition of voice over for same text.
=> Remove new line character before setting accessibility text to avoid repetition of voice over for same text.

SVProgressHUD.podspec
Fixes #432
It's really an old issue but I think everyone can benefit from this small change when dealing with CocoaPods and App Extensions. Using subspecs is basically "how it should be done", see: https://github.com/CocoaPods/CocoaPods/issues/5373#issuecomment-220486539
=> App Extension compatibility in Podspec

Demo/SVProgressHUD-Info.plist
Currently when opening Demo/SVProgressHUD.xcodeproj, the iOS Demo scheme cannot be run. An error message indicating the CFBundleShortVersionString key is missing from the Info.plist.
=> Fix demo app doesn’t run without CFBundleShortVersionString key

SVProgressHUD/SVIndefiniteAnimatedView.m
This allows us to position SVIndefiniteAnimatedView with Auto Layout while keeping the animated layer’s frame correctly centered.
=> Make SVIndefiniteAnimatedView update its sublayer on layoutSubviews

SVProgressHUD/SVProgressHUD.m
when I set  setImageViewSize(.zero), hudView will show a top margin
`---------------------------------------------------------------------------------------------------------------------`
After modification
=> Update imageUsed judgment conditions when set imageViewSize to zero
