SVProgressHUD/SVProgressHUD

README.md
SVProgressHUD-Framework/Info.plist
SVProgressHUD-Framework/SVProgressHUD-Framework.h
SVProgressHUD.xcodeproj/project.pbxproj
SVProgressHUD.xcodeproj/xcshareddata/xcschemes/SVProgressHUD-Framework.xcscheme

Adds support for CocoaTouch framework and Carthage installation

Adds framework support

---

SVProgressHUD/SVProgressHUD.h
SVProgressHUD/SVProgressHUD.m

Having the corner radius of the HUD view customizable would be a nice addition.

Allow hudView.layer.cornerRadius to be customizable

---

SVProgressHUD/SVProgressHUD.m

Added accessibility support so that it's visible while using iOS 9 new feature: UI Recording

Added accessibility support

---

SVProgressHUD/SVProgressHUD.m

A potential approach for fixing the issue.

Fix the issue https://github.com/TransitApp/SVProgressHUD/issues/481.

---

SVProgressHUD/SVProgressHUD.m

SVProgressHUD is not working with Extensions. 
*SVProgressHUDExtensionView is not defined at any time, so it doesn't build. It should be viewForExtension.
*The second change is a duplicated line that breaks the build too.
After these minor fixes, it works like a charm.

Fixing build problems when using SV_APP_EXTENSIONS macro

---

SVProgressHUD/SVProgressHUD.m

Resolved the backgroundLayer frame misalignment issue in device orientation changes.

Fixing the Background Mask Misplacing issue

---

SVProgressHUD/SVProgressHUD.m

Changed a wrong #ifndef validation for the correct one (#if)

Fixes #490. No supported interface orientation in real time

---

SVProgressHUD/SVProgressHUD.m

`SVProgressHUDDidAppearNotification` should be `SVProgressHUDDidDisappearNotification`.

fix: should be `SVProgressHUDDidDisappearNotification`.

---

SVProgressHUD-Framework/Info.plist
SVProgressHUD.xcodeproj/project.pbxproj
SVProgressHUD.xcodeproj/xcshareddata/xcschemes/SVProgressHUD-Framework.xcscheme

Fixes #585
Cleaned up a few different settings in the Framework target for Carthage. I pointed our project at my branch and it builds without issue. 
Bonus points if you want to run the commands below and add the zip file output to the git tags. Then Carthage can just download that zip file and use the binaries inside rather than having to burn CPU cycles rebuilding the project from scratch.
`carthage build --no-skip-current`
`carthage archive`

Fixed Carthage support.

---

SVProgressHUD.xcodeproj/project.pbxproj

I added SVProgressAnimatedView.m/h files to project, because building on Xcode or carthage failed by missing the files.

Add missing files

---

README.md
SVProgressHUD/SVProgressHUD.h
SVProgressHUD/SVProgressHUD.m

https://github.com/SVProgressHUD/SVProgressHUD/issues/119

Add HUD to UIView instead of UIWindow

---

SVProgressHUD/SVProgressHUD.m

I believe I was able to fix #711 by checking the frontWindow for being the keyWindow before injecting the view.

fix for #711

---

SVProgressHUD/SVProgressHUD.m

Fixes https://github.com/SVProgressHUD/SVProgressHUD/issues/771

Stop calling UIAccessibilityScreenChangedNotification on dismiss

---

SVProgressHUD/SVProgressHUD.h
SVProgressHUD/SVProgressHUD.m

To let people set images larger than 28x28 pt.

Add the posibility to change the size image view

---

SVProgressHUD/SVProgressHUD.m

adjust the hudView offset when show in the containerView

adjust the hudView offset when show in the containerView

---

SVProgressHUD/SVProgressHUD.h

Dear author, here is a pen, this framework is great, thank you

Typo in setBackgroundLayerColor: description

---

Demo/Base.lproj/Main.storyboard
Demo/Classes/ViewController.h
Demo/Classes/ViewController.m
Demo/SVProgressHUD.xcodeproj/project.pbxproj
README.md
SVProgressHUD/SVProgressHUD.h
SVProgressHUD/SVProgressHUD.m

According to @zsjenei - #823 
Rollback of popActivity change + update of demo app to show that popActivity actually worked fine.
@honkmaster - refer to this issue please. You removed really serious feature here.

Rollback of popActivity

---

SVProgressHUD/SVProgressHUD.m

Fixed typo:
everyting -> everything

Everything

---

SVProgressHUD/SVProgressHUD.h
SVProgressHUD/SVProgressHUD.m

Another approach to fix #950 
I just make static configuration to allow set enabled/disabled motion effects.

Added ability to set motion effects disabled

---

SVProgressHUD/SVProgressHUD.m

Fix template image usage

---

SVProgressHUD/SVProgressHUD.m

Now if user changes system font size within Settings the progress hud will also apply these changes

Added adjustFontForContentSizeCategory to statusLabel

---

SVProgressHUD/SVIndefiniteAnimatedView.m

Fixed memory leak while loading image from bundle
